# Project: 4.4
# Makefile created by Dev-C++ 5.10

CPP      = g++.exe -D__DEBUG__
CC       = gcc.exe -D__DEBUG__
WINDRES  = windres.exe
OBJ      = numdays.o main.o main4.5.o
LINKOBJ  = numdays.o main.o main4.5.o
LIBS     = -L"C:/Users/Kendall/Desktop/C++/Dev-Cpp/MinGW64/lib" -L"C:/Users/Kendall/Desktop/C++/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc -g3
INCS     = -I"C:/Users/Kendall/Desktop/C++/Dev-Cpp/MinGW64/include" -I"C:/Users/Kendall/Desktop/C++/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Users/Kendall/Desktop/C++/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.8.1/include"
CXXINCS  = -I"C:/Users/Kendall/Desktop/C++/Dev-Cpp/MinGW64/include" -I"C:/Users/Kendall/Desktop/C++/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Users/Kendall/Desktop/C++/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.8.1/include" -I"C:/Users/Kendall/Desktop/C++/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.8.1/include/c++"
BIN      = 4.4.exe
CXXFLAGS = $(CXXINCS) -g3
CFLAGS   = $(INCS) -g3
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

numdays.o: numdays.cpp
	$(CPP) -c numdays.cpp -o numdays.o $(CXXFLAGS)

main.o: main.cpp
	$(CPP) -c main.cpp -o main.o $(CXXFLAGS)

main4.5.o: main4.5.cpp
	$(CPP) -c main4.5.cpp -o main4.5.o $(CXXFLAGS)
