# Project: Project2
# Makefile created by Dev-C++ 5.10

CPP      = g++.exe -D__DEBUG__
CC       = gcc.exe -D__DEBUG__
WINDRES  = windres.exe
OBJ      = classic.o main.o series.o scoring.o
LINKOBJ  = classic.o main.o series.o scoring.o
LIBS     = -L"C:/Users/Kendall/Desktop/C++/Dev-Cpp/MinGW64/lib" -L"C:/Users/Kendall/Desktop/C++/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc -g3
INCS     = -I"C:/Users/Kendall/Desktop/C++/Dev-Cpp/MinGW64/include" -I"C:/Users/Kendall/Desktop/C++/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Users/Kendall/Desktop/C++/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.8.1/include"
CXXINCS  = -I"C:/Users/Kendall/Desktop/C++/Dev-Cpp/MinGW64/include" -I"C:/Users/Kendall/Desktop/C++/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Users/Kendall/Desktop/C++/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.8.1/include" -I"C:/Users/Kendall/Desktop/C++/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.8.1/include/c++"
BIN      = Project2.exe
CXXFLAGS = $(CXXINCS) -g3
CFLAGS   = $(INCS) -g3
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

classic.o: classic.cpp
	$(CPP) -c classic.cpp -o classic.o $(CXXFLAGS)

main.o: main.cpp
	$(CPP) -c main.cpp -o main.o $(CXXFLAGS)

series.o: series.cpp
	$(CPP) -c series.cpp -o series.o $(CXXFLAGS)

scoring.o: scoring.cpp
	$(CPP) -c scoring.cpp -o scoring.o $(CXXFLAGS)
